### ISSUE TITLE
Prevent add of same sample in DB when parsing folder

### ISSUE THREAD

**Issue by garanews** [JPCERTCC/impfuzzy#4]
Launching the command:
python impfuzzy_for_neo4j.py -d /myfolder/
If in myfolder are present 2 samples with different names but same hash, the script will add in DB both samples and not only one, going to create cluster with itself.

**Comment by garanews** [comment]
this will fix it:
https://github.com/JPCERTCC/impfuzzy/pull/3/commits/27373f313c2e1c9ada53e705c87ef1fd34238f6f

**Comment by shu-tom** [comment]
Thank you for pull request. I merged it.
